function skillsMember() {
  var member = new Member();
  member.skills = [
    new Skill('JavaScript', 5),
    new Skill('Node.js', 5),
    new Skill('AngularJS', 4),
    new Skill('HTML', 5),
    new Skill('CSS', 5),
    new Skill('SASS', 4),
    new Skill('Gulp', 4),
    new Skill('Grunt', 4),
    new Skill('Git', 5),
    new Skill('PHP', 4),
    new Skill('MySQL', 4),
    new Skill('MongoDB', 4),
    new Skill('Java', 4),
    new Skill('C++', 4),
    new Skill('Python', 3),
    new Skill('Ruby', 3),
    new Skill('C#', 3),
    new Skill('Objective-C', 2),
    new Skill('Swift', 3),
    new Skill('Photoshop', 4),
    new Skill('Illustrator', 4),
    new Skill('InDesign', 3),
    new Skill('Flash', 3),
    new Skill('After Effects', 3),
    new Skill('Premiere', 3),
    new Skill('Final Cut', 3),
    new Skill('Blender', 3),
    new Skill('Cinema 4D', 3),
    new Skill('Unity', 2),
    new Skill('Maya', 2),
    new Skill('3ds Max', 2),
    new Skill('ZBrush', 2),
    new Skill('AutoCAD', 2),
    new Skill('SketchUp', 3),
    new Skill('Rhino', 2),
    new Skill('SolidWorks', 2),
    new Skill('Inventor', 2),
    new Skill('Revit', 2),
    new Skill('Photoscan', 2),
    new Skill('Agisoft', 2),
    new Skill('Mudbox', 2),
    new Skill('Substance', 2),
    new Skill('Mari', 2),
    new Skill('Modo', 2),
    new Skill('Lightwave', 2),
    new Skill('Houdini', 2),
    new Skill('Nuke', 2),
    new Skill('Fusion', 2),
    new Skill('Flame', 2),
  ]
}